### PR TITLE
:bug: Clean Twig tag to fix issues with last versions of Twig

### LINKED ISSUE #67: "Error: Call to undefined method Twig\Environment::getTags()" with Twig 3.2
```php
Error: Call to undefined method Twig\Environment::getTags()
```

See https://github.com/notFloran/mjml-bundle/blob/4fe98378d69613edbe408a07c0f0e4853f821fb6/src/Twig/Node.php#L35

### PR DESCRIPTION
**Pull request by notFloran**
Fix #67

### CODE REVIEW

File: src/Twig/Node.php [hunk 1]
```diff
@@ -32,9 +39,6 @@ public function compile(Compiler $compiler)
             ->write('$lines = explode("\n", $content);'.PHP_EOL)
             ->write('$content = preg_replace(\'/^\' . $matches[0]. \'/\', "", $lines);'.PHP_EOL)
             ->write('$content = implode("\n", $content);'.PHP_EOL)
-            ->write('echo $this->env->getTags()["mjml"]
```
Comment (notFloran) [inline src/Twig/Node.php:35]: No more `getTags` with Twig 3.2, see https://github.com/twigphp/Twig/commit/81751d6671a42b7a7187dba23ae00cbe1e0082e3#diff-a649e8fcd77d506cd5ef3e00f495e87c0583b3bdee1ea0e953d9f9c2681a39e2
